baseURL: "https://blog.yoryo.io/"
languageCode: en-us
title: Blog
theme: PaperMod

params:
  defaultTheme: dark
  disableThemeToggle: true
  homeInfoParams:
    Title: Hi, welcome to my blog! wave
    Content: Threat intelligence, vulnerability research and exploit development... :)
